#############################################################################
# DATABASE CONNECTIONS
#############################################################################
# MySQL/MariaDB both require a user and password authentication.  That is 
# stored here as encrypted information.  
#############################################################################
# SQL Server uses passthrough credentials, meaning that you must be logged 
# onto the hutch network in order to pass your credentials throuh to SQL 
# Server.  If working off-site you need to have a VPN connection to hutch.local.
#############################################################################
# Configurations
#############################################################################
# Connections are set up during instantiation of icicle functions.
# Functions decrypt configurations as needed via a keychain stored on PC/MAC.
# During that first connection attempt from each PC/MAC users provide the
# encryption key "aml*****!" which is stored on the PC/MAC keychain.
#############################################################################

[sqlserver]
# bare bones to use when accessing schemas other than the esteylist.
database = HEMEDB
driver = ODBC Driver 17 for SQL Server
server = SQLPRDGEN01
database = HEMEDB
trusted_connection = yes

[mariadb]
# bare bones to use when accessing any mariadb schema
engine = MariaDB
user = jappelb
encrypted_password = 2iULpUgzRmIpmKPybrMrL6KtE4XQjnkXTA==
host = mydb
connection = hemedbstage
port = 32338

[mysql]
# for use when connecting to MySQL
user = carole_shaw
encrypted_password = mhk0BhUpKLXO0KPQy6ND3ZO5FI3Wu2ofVuwvzZRLbaFi9TU+HB3Urg==
engine = MariaDB
host = MYSQL-DB-PRD
port = 3306
schema = caisis

[jake_mysql_r]
# for use when connecting to MySQL
user = jake_appelbaum
encrypted_password = AZyRdJCyuSkiNnJOR6AM9bG+CIbRhngCUe1yiv8WLvIi
engine = MYSQL
host = MYSQL-DB-PRD
port = 3306

#############################################################################
# RED CAP CONNECTIONS
#############################################################################
# Each REDCap project has it's own unique token, encrypted here
# and some REDCap projects are hosted at ITHS, while some are at FHCC.  The
# url varies by host site.  No password is required to access the
# REDCap data via the API
#############################################################################

[diagnosis_for_aml_arrivals]
#####################
section = diagnosis_for_aml_arrivals
schema = diagnosis_for_aml_arrivals
#####################
# for use when connecting directly to REDCap
url = https://redcap.fredhutch.org/api/
# 2653C5531DFB3944EAEB5F23D31AEE54
encrypted_token = Mtr7fqJ4CyNj7QOibcPC9fP6UtL83D5FCcoG+P0XO+dGx0FOGn7DuIuVrpxVcxsw
# REDCap fields to replicate into every table when moving to a database
keyfields = diagnosisid, ptmrn, recordid
# REDCap tables to retain
retain = disease_features, trm, biasstudy, eln, induction, response, relapse
#####################
# for use when connecting to sqlserver
database = HEMEDB

[playground]
#####################
section = playground
schema = playground
#####################
# for use when connecting directly to REDCap
url = https://redcap.fredhutch.org/api/
encrypted_token = ScjA9S/a7Cr86mu7AwWfWYT1U9GP0T9OCLpxjPoeNpJBszRNHQHIsvfgpp4iBhZF
# REDCap fields to replicate into every table when moving to a database
keyfields = arrival_id, ptmrn, ptlastname
# REDCap tables to retain
retain = demographics, mbp_breems_redux, playground, playgroundoutcomes, relapse_in_nd_patients_missing_relapse
#####################
# for use when connecting to sqlserver
database = HEMEDB
# reports that would be nice to retain:  allfields, playgroundkey

[mpal]
#####################
section = mpal
schema = mpal
#####################
# for use when connecting directly to REDCap
url = https://redcap.iths.org/api/
encrypted_token = Q6nNBdqtJ0HHbE8FILlMnvL1XtL+qD5BDsgDjYhsOOdAtDRPFn3Hs/+W3etRDxhF
# REDCap fields to replicate into every table when moving to a database
keyfields = recordid, patlistid, ptmrn, ptlastname
# REDCap tables to retain
retain = potential_mpal_patients, mpal_treatment_review, transplant_service, patient_list, calculatedfields, epic_demographic_data, mutations, ngs_caisis
#####################
# for use when connecting to sqlserver
database = HEMEDB

[esteylist]
#####################
section = esteylist
schema = esteylist
#####################
# for use when connecting directly to REDCap
url = https://redcap.iths.org/api/
encrypted_token = BGVq4UttUYrevqVskDUVGoCNVdaLqzJOAcp2iPsfTuY2wDM9bgqzufqSqeVVDxdH
# REDCap fields to replicate into every table when moving to a database
keyfields = recordid, ptmrn, ptlastname
# REDCap tables to retain
retain = shorttest, patient_list, dx_mutations, arrival1, arrival2, arrival3, arrival4, arrival5, arrival6, arrival7, arrival8, arrival9, arrival10, arrival11, specialty_note, eln2022, trm, ee20_paper, kd2008_newlydiagnosed, kd2018_newlydiagnosed, induction, caisis_pathology_tests, transplant_service, redcap_dx_trm
#####################
# for use when connecting to mariadb
# engine = MARIA
# user = jappelb
# encrypted_password = 2iULpUgzRmIpmKPybrMrL6KtE4XQjnkXTA==
# host = mydb
# connection = hemedbstage
# port = 32338
#####################
# for use when connecting to sqlserver
database = HEMEDB


[breems]
#####################
section = breems
schema = breems
#####################
# for use when connecting directly to REDCap
url = https://redcap.iths.org/api/
encrypted_token = ugIg1LMXW8FEa2b+DnZiUIOKIdOG2EpACLp4jPoYP+A0szc7HACwuYuRq5xWcm1A
# REDCap fields to replicate into every table when moving to a database
keyfields = breemsid, ptmrn, ptlastname
# REDCap tables to retain
retain = breems, patient_list, noam_kopmar_breems_year_summary
#####################
# for use when connecting to sqlserver
database = HEMEDB


[dahlia]
# test redcap installation
section = dahlia
schema = dahlia
# for use when connecting directly to dahlia REDCap project
url = https://redcap.iths.org/api/
encrypted_token = dbP8nc9fTC7jjQ6AG0G4yoOJX9CPrTJHfrpwj4gdTZBAtjc+bXrHyf+frO4gAx1C